config/routes.rb
Rails.application.routes.draw do
  
  resources :events, only: [:index, :new]

  resources :events, only: [:index, :create, :update, :destroy], path: '/api/events', defaults: {format: :json}

  resources :categories

  resources :articles do 
  resources :comments, only: [:create, :destroy, :update]
  end

  devise_for :users
  get 'index' => 'home#index'
  #ruta con nombre asignado
  get 'home/index'
  #ruta creada por el comando rails generate controller
  root 'home#index'
  #ruta root del proyecto

  get 'dashboard'  => 'home#dashboard'
  get "/articles/:id/publish", to: "articles#publish"
  get "/articles/:id/in_draft", to: "articles#draft"

end

app/models/article.rb
class Article < ActiveRecord::Base
	include AASM

	validates :title, presence: true, uniqueness: true
	validates :body, presence: true , length: {  minimum: 5 , message: "%{value} You must have minimum 5 characters"}
	belongs_to :user
	has_many :comments
	has_many :has_categories
	has_many :categories, through: :has_categories
	mount_uploader :avatars, AvatarUploader
	after_commit :remove_avatars!, on: :destroy
	after_commit :remove_previously_stored_avatar, on: :update
	before_create :set_visits_count
	#validates :avatars, presence: true
	after_create :save_categories
	
	scope :publicados, ->{ where(state: "published") } 

	def categories=(value)
		@categories = value
	end
	def update_visits_count
		self.update(visits_count: self.visits_count + 1)
	end
	def update_categories

		delete = HasCategory.where(article_id: self.id)
		if  delete ||= nil
			delete.each do |del_has_category|
				del_has_category.destroy
			end

		end
	    unless  @categories.nil? 
			@categories.each do |category_id|
			HasCategory.create(category_id: category_id,article_id: self.id)
			end
		end
	end

	aasm column: "state" do
		state :in_draft, initial: true
		state :published

		event :publish do
			transitions from: :in_draft, to: :published
		end
		event :unpublish do
			transitions from: :published, to: :in_draft
		end
	end	

	private

	def save_categories
		if  @categories ||= nil
			@categories.each do |category_id|
			HasCategory.create(category_id: category_id,article_id: self.id)
			end
		end
	end

	def set_visits_count
		self.visits_count = 0
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :edit]
	before_action :set_article, except: [:index, :new, :create]
	before_action :authenticate_editor!, only: [:new, :create, :update]
	before_action :authenticate_admin!, only: [:destroy, :publish]
	
	def index
		@articles = Article.paginate(:page => params[:page], :per_page => 7).publicados
	end
	def show
		@comment = Comment.new
		@articles.update_visits_count	

		respond_to do |format|
			format.html
			format.pdf do
				pdf = ArticlePdf.new(@articles)
				send_data pdf.render, filename: "Articulo_#{@articles.title}.pdf",
										type: "application/pdf",
										disposition: "inline"
						#pdf = Prawn::Document.new(:page_size => [1000, 20000])
		#pdf = Prawn::Document.new(:page_size => '2A0')
		#pdf = Prawn::Document.new(:page_layout => :landscape)
			end
		end	
	end
	def new
		@articles = Article.new
	end
	def edit
		
	end
	def update
		   @articles.categories = params[:categories]
		   @articles.update_categories
		if @articles.update(article_params)		   
		redirect_to @articles
		else 
		render :edit
		end
	end
	def create
		@articles = current_user.articles.new(article_params)			
		@articles.categories = params[:categories]
		if @articles.save
    		redirect_to @articles
        else
        	render :new
       end		
	end
	def destroy
		
	    @articles.destroy
	    redirect_to articles_path
	end

	def publish
		@articles.publish!
		redirect_to @articles
	end
	
	def draft
		@articles.unpublish!
		redirect_to @articles
	end

	private 
	def set_article
		@articles = Article.find(params[:id])
	end
	def article_params
       params.require(:article).permit(:title, :body, :avatars, :categories)
    end

end

app/views/articles/edit.html.erb
<%= render "partial/index" %>
<div class="row">

	<div class="col-md-6">

  <% if @articles.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @articles.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render "partial/form", name: "Edit" %>
		
	</div>  

</div>

app/views/articles/index.html.erb
<%= render "partial/index" %>
<div class="row">

	<div class="col-md-12">
<h2>
	Articles
</h2>
<div class="row">
<% @articles.each do |art| %>
	<div class="col-md-4">
		<h4><%= link_to art.title, article_path(art) %></h4>	

		<% if art.avatars?%>
		<%=	image_tag(art.avatars.thumb.url , class:"redonda") %>
		<% else %>
		<img src="/uploads/article/avatars/10/thumb_surfranchlogovector_0.png">
		<% end %>
	    <% if user_signed_in? %>
        <p><%= truncate(art.body, length:20) %> - <%= link_to "Delete", art, method: :delete  %></p>        
        <% else %>
        <p><%= art.body %></p>        
        <% end %>		
		
	<p>Visits: <%= art.visits_count %> - <%= time_ago_in_words(art.created_at) %> ago - Created <%=	image_tag(art.user.avatar , class:"redonda") %></p>

	</div>
<%end%>	
</div>

	


<%= will_paginate @articles %>

    </div>

</div>

app/views/articles/new.html.erb
<%= render "partial/index" %>

<div class="row">

	<div class="col-md-6">

  <% if @articles.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @articles.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
		<%= render "partial/form" , name: "New" %>
	</div>  

</div>

app/views/articles/show.html.erb
<%= render "partial/index" %>
<div class="row">
	<h2>
	Article
    </h2>
	<div class="col-md-6">
	<h4>Write by: <%= @articles.user.email %></h4>
	<h4><%= @articles.title %></h4> <% @articles.categories.each do |cat| %> <%= link_to cat.name, cat, style:"color:#{cat.color}" %><% end %>

		<p><%= @articles.body %> -  <%= link_to "Edit", edit_article_path(@articles) %> - <%= link_to "Generar PDF", article_path(@articles, format: "pdf") %></p> 
	

	<p>Visits: <%= @articles.visits_count %></p>
	<h2>
	Comments
    </h2>

    <table>
	  <thead>
	    <tr>
	      <th>User</th>
	      <th>Article</th>
	      <th>Body</th>
	    </tr>
	  </thead>

	  <tbody id="comments-box">
	    <% @articles.comments.each do |comment| %>
	   
	      <tr>
	        <td><%= comment.user.email %> </td>
	        <td><%= comment.article.title %> </td>
	        <td><%= comment.body %></td>	        
	      </tr>

	    <% end %>

	 
	  </tbody>
	</table>

<h4>new comment</h4>
    <%= form_for([@articles,@comment], remote: true, html: { id: "comments-form" ,:"data-type" => "json"}) do |f| %>  
	  
	  <div class="field">
	    <%= f.label :body %><br>
	    <%= f.text_area :body %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>

    </div>

</div>